export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_LOADING = 'DELETE_PRODUCT_LOADING';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const GET_PRODUCT_BYID_LOADING = 'GET_PRODUCT_BYID_LOADING';
export const GET_PRODUCT_BYID_SUCCESS = 'GET_PRODUCT_BYID_SUCCESS';
export const GET_PRODUCT_BYID_ERROR = 'GET_PRODUCT_BYID_ERROR';

export const POST_PRODUCT_LOADING = 'POST_PRODUCT_LOADING';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR';

export const PUT_PRODUCT_LOADING = 'PUT_PRODUCT_LOADING';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_ERROR = 'PUT_PRODUCT_ERROR';